CREATE TABLE Uzytkownik (
	UzytkownikID INT IDENTITY(1, 1) PRIMARY KEY,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Nazwisko NVARCHAR(50) NOT NULL,
	Imie NVARCHAR(50) NOT NULL,
	Telefon NVARCHAR(20) NULL,
	DataRejestracji DATETIME NOT NULL DEFAULT GETDATE(),
	HasloHash NVARCHAR(255) NOT NULL
);
